name: Telegram Bot

on:
  schedule:
    - cron: '0 */5 * * *'   # 每5小时触发一次
  workflow_dispatch:
  push:
    branches: [ "main" ]

# 关键：并发控制，同一时间只允许一个运行
concurrency:
  group: telegram-bot-run
  cancel-in-progress: true   # 如果新的运行开始，取消旧的

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --timeout 1000
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ZWFW_TOKEN: ${{ secrets.ZWFW_TOKEN }}
          CNA: ${{ secrets.CNA }}
          JSESSIONID: ${{ secrets.JSESSIONID }}
          SESSION: ${{ secrets.SESSION }}
          SERVERID: ${{ secrets.SERVERID }}
          OKPAY_ID: ${{ secrets.OKPAY_ID }}
          OKPAY_TOKEN: ${{ secrets.OKPAY_TOKEN }}
          CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
        run: |
          python bot.py
